@startuml
skinparam backgroundColor transparent
title  \n観戦記録情報閲覧 BUC\n 

rectangle "情報\n観戦記録" as infoRecord
rectangle "画面\n観戦記録閲覧" as viewShow

rectangle "Act\n観戦記録情報を閲覧する" as actShow

left to right direction

:ユーザ: -- actShow

"UC\n観戦記録情報を閲覧する" as (ucRecordShow)

actShow -- ucRecordShow
ucRecordShow -- infoRecord
ucRecordShow -- viewShow

@enduml